sudo: false
language: objective-c
osx_image: xcode7.1
cache: cocoapods
podfile: SwiftlineTests/Podfile

before_install:
- gem install cocoapods-rome
- pod install --project-directory=SwiftlineTests --no-integrate

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- make test
- cd ..; pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
